version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - strapi-backend-db:/var/lib/postgresql/data

  strapi-backend:
    build:
      context: .
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  strapi-backend-db:
